name: flutterstrap_ui
description: "A Flutter package to create responsive layouts. Designed to handle responsive layouts in Flutter web projects, it works for any platform."
version: 1.0.0
homepage: https://github.com/elchief84/flutterstrap

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
